# Generated by Django 4.1 on 2022-08-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_url_last_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='owner',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
