# Generated by Django 4.1 on 2022-08-31 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_url_desktop_clicks_url_mobile_clicks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='owner',
            field=models.CharField(blank=True, default='Anonymous User', max_length=1000),
        ),
    ]
